### ISSUE TITLE
Requirement is pinned for pyskyqhub 0.1.0: aiohttp==3.6.2

### ISSUE THREAD

**Issue by MartinHjelmare** [RogerSelwyn/skyq_hub#2]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by RogerSelwyn** [comment]
I'm working towards changing this to >=3.6.2. Just testing out an updated version of the module before putting a PR into HA.

**Comment by RogerSelwyn** [comment]
Close with the PR submitted to HA core
